# Generated by Django 5.2 on 2025-04-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(default=0, max_length=10, unique=True, verbose_name='Placa'),
        ),
    ]
