# Generated by Django 5.2 on 2025-05-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('em_servico', 'Em Manutenção')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
