# Generated by Django 5.2 on 2025-04-23 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflows',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrada de produto', 'verbose_name_plural': 'Entrada de produtos'},
        ),
    ]
